version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gateway:
    build: ../../services/gateway
    image: tokenised/gateway:dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    depends_on:
      - postgres
      - redis
  orchestrator:
    build: ../../services/orchestrator
    image: tokenised/orchestrator:dev
    ports:
      - "9080:9080"
    environment:
      - NODE_ENV=development
      - PORT=9080
    depends_on:
      - postgres
      - redis

  oracle-sim:
    image: node:20-alpine
    command: ["sh", "-c", "sleep 3600"]

  tariff:
    build: ../../services/tariff
    image: tokenised/tariff:dev
    ports:
      - "9090:9090"

  billing:
    build: ../../services/billing
    image: tokenised/billing:dev
    ports:
      - "9091:9091"

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ["--host", "0.0.0.0", "--port", "8545", "--accounts", "10"]
    ports:
      - "8545:8545"

volumes:
  db_data:
    
networks:
  default:
    driver: bridge
