name: CI

on: [push, pull_request]

jobs:
  gateway:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install gateway deps
        run: |
          cd services/gateway
          npm install
      - name: Run gateway smoke test
        run: |
          cd services/gateway
          npx ts-node test/run_and_test.ts

  orchestrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install orchestrator deps
        run: |
          cd services/orchestrator
          npm install
      - name: Run orchestrator health check
        run: |
          curl -sS http://localhost:9080/health || true
