iname: Deploy to Cloud Run

on:
  push:
    branches: [master]
    tags: ['v*']

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Test Gateway
        run: |
          cd services/gateway
          npm ci
          npm test
      - name: Test Contracts
        run: |
          cd contracts
          forge install
          forge test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy Services
        run: |
          echo "🚀 Deploying tokenised API credits system..."
          
          # Deploy gateway
          gcloud run deploy gateway \
            --source services/gateway \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 8080 \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10
            
          # Deploy orchestrator  
          gcloud run deploy orchestrator \
            --source services/orchestrator \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 9080
            
          echo "✅ Deployment complete!"
          echo "Gateway URL: $(gcloud run services describe gateway --region=$REGION --format='value(status.url)')"
          echo "Orchestrator URL: $(gcloud run services describe orchestrator --region=$REGION --format='value(status.url)')"
